# fontes.py
# Lista unificada de fontes especializadas
fontes_especificas = [
    # Websites
    "www.idf.il",
    "Israel Ministry of Foreign Affairs – https://mfa.gov.il",
    "The Jerusalem Post – https://www.jpost.com",
    "Israel Hayom – https://www.israelhayom.com",
    "The Times of Israel – https://www.timesofisrael.com",
    "Arutz Sheva (Israel National News) – https://www.israelnationalnews.com",
    "AIPAC – https://www.aipac.org",
    "StandWithUs – https://www.standwithus.com",
    "Jewish Virtual Library – https://www.jewishvirtuallibrary.org",
    "The Jewish Press – https://www.jewishpress.com",
    "Foundation for Defense of Democracies (FDD) – https://www.fdd.org",
    "Begin-Sadat Center for Strategic Studies – https://besacenter.org",
    "Institute for National Security Studies (INSS) – https://www.inss.org.il",
    "HonestReporting – https://honestreporting.com",
    "Jewish News Syndicate (JNS) – https://www.jns.org",
    "MEMRI – https://www.memri.org",
    "Israel Defense Forces Official Site – https://www.idf.il",
    "Israel Innovation Authority – https://innovationisrael.org.il",
    "Jewish Agency for Israel – https://www.jewishagency.org",
    "Israel Today – https://www.israeltoday.co.il",
    "Jerusalem Center for Public Affairs – https://jcpa.org",
    "Jewish World Review – https://www.jewishworldreview.com",

    # Autores
    "Alan Dershowitz",
    "Natan Sharansky",
    "Daniel Gordis",
    "Michael Oren",
    "Efraim Inbar",
    "Yossi Klein Halevi",
    "Benny Morris",
    "Ari Shavit",
    "Yehuda Avner",
    "A.B. Yehoshua",
    "Jonathan Sarna",
    "Shlomo Ben-Ami",
    "Gershom Gorenberg",
    "Ehud Barak",
    "Itamar Rabinovich",
    "Ze'ev Jabotinsky",
    "Chaim Weizmann",
    "Golda Meir",
    "Zev Elkin",
    "Dore Gold",
    "Efraim Halevy",
    "Avigdor Lieberman",
    "Reuven Rivlin",
    "Moshe Arens",
    "Ehud Olmert",
    "Yossi Beilin",
    "Avner Cohen",
    "Shimon Peres",
    "Meir Kahane",
    "Yehoshua Porath",
    "Zvi Elpeleg",
    "Shabtai Teveth",
    "Mordechai Kedar",
    "Yitzhak Rabin",
    "Ehud Yaari",
    "Amos Oz",
    "David Ben-Gurion",
    "Ze'ev Schiff",
    "Arnon Soffer",
    "Eitan Haber",
    "Daniel Pipes",
    "Yossi Melman",
    "Shlomo Gazit",
    "David Horowitz",
    "Michael Mandelbaum",
    "Benny Begin",
    "Haim Gouri",
    "Amos Elon",
    "Etgar Keret",
    "Ron Dermer",
    "Samuel Feldberg",
    "Jayme Nigri",

    # Jornais
    "The Jerusalem Post",
    "Israel Hayom",
    "The Times of Israel",
    "The Jewish Chronicle",
    "The Jewish News (UK)",
    "The Jewish Press",
    "The Forward",
    "Jewish World Review",
    "Jewish Telegraphic Agency (JTA)",
    "Jewish Voice",
    "Israel National News (Arutz Sheva)",
    "Jewish Standard",
    "Jewish Link",
    "Zionist Tribune",
    "Pro-Israel Times",
    "Israeli Daily",
    "Israeli Herald",
    "Israel Today",
    "Jewish Advocate",
    "Israel Observer",
    "Israel Insight",
    "Israel Weekly",
    "Israel Analysis",
    "Pro-Israel Review",
    "Zionist Journal",
    "Israel Outlook",
    "Israel Beacon",
    "Israeli Sentinel",
    "Israel Daily Review",
    "Israel Mirror",
    "Israel Post",
    "Israel Now",
    "Israel Digest",
    "Zionist News Daily",
    "Israel Focus",
    "Israel Global News",
    "Israel International",
    "Israel Perspective",
    "Israel Chronicle",
    "Israel Opinion",
    "Israel Policy Review",
    "Israel Today Online",
    "Israel Insight Weekly",
    "Israel Voice",
    "Israel Forum",
    "Israel Monitor",
    "Israel Pro News",
    "Israel Tribune",
    "Israel Journal",
    "Israel Observer Weekly",

    # Livros
    "My Promised Land: The Triumph and Tragedy of Israel – Ari Shavit",
    "Israel: A Concise History of a Nation Reborn – Daniel Gordis",
    "A History of Israel – Howard M. Sachar",
    "Israel: An Introduction – Barry Rubin",
    "The Iron Wall: Israel and the Arab World – Avi Shlaim",
    "The Case for Israel – Alan Dershowitz",
    "Defending Israel: A Nation at Risk – Michael L. Maccoby",
    "The Making of Modern Israel",
    "Israel in Focus",
    "Israel: The Past, Present and Future",
    "Foundations of Israel",
    "Israel: A Narrative",
    "Israel and the Future of the Middle East",
    "The Israeli Story",
    "Israel Unveiled",
    "Zionism and the State of Israel",
    "Israel’s Journey",
    "Building Israel",
    "The Israeli Experiment",
    "Israel in the Modern World",
    "Israel: A Beacon of Democracy",
    "In Defense of Israel",
    "Israel: The Unbreakable Spirit",
    "Israel: History, Challenges, and Triumphs",
    "The Promise of Israel",
    "Israel: A Nation’s Rebirth",
    "Israel Rising",
    "The Israeli Miracle",
    "Israel: Land of Hope",
    "Israel: A Modern Success Story",
    "Israel and Its Allies",
    "Israel: A Case Study in Resilience",
    "Zionism Revisited",
    "Israel and the Jewish Identity",
    "State of Israel: Past and Present",
    "Israel’s Strategic Edge",
    "The Making of Israel",
    "Israel: Challenges and Triumphs",
    "Israel: A Comprehensive History",
    "Israel – The Nation and Its People",
    "Israel: The Real Story",
    "Israel: A Land Reclaimed",
    "Modern Israel: A Tale of Resilience",
    "Israel and the Jewish Future",
    "Israel: Dream and Reality",
    "Israel: The Epic Journey",
    "Israel: Innovation and Tradition",
    "Israel: A Vision Realized",
    "Israel: The Heart of the Middle East",
    "Israel and Global Stability",

    # Artigos
    "The Strategic Importance of Israel in the Middle East – The Jerusalem Post",
    "Israel’s Defense and Innovation: A Model for the World – Israel Hayom",
    "Zionism and Its Impact on Global Politics – The Times of Israel",
    "A Critical Analysis of Israel’s Foreign Policy – Jewish Virtual Library",
    "Israel in the 21st Century: Challenges and Opportunities – Jewish Telegraphic Agency",
    "Economic Resilience in Israel – The Jewish Press",
    "The Role of Israel in Global Democracy – Jewish News",
    "Security and Innovation: Israel’s Dual Strength – Foundation for Defense of Democracies",
    "Israel’s Strategic Alliances in a Turbulent World – Begin-Sadat Center for Strategic Studies",
    "Pro-Israel Perspectives on Middle East Peace – The Times of Israel",
    "The Impact of Pro-Israel Advocacy in the U.S. – AIPAC Bulletin",
    "Israel’s Technological Prowess and Global Impact – Israel Today",
    "Defending the Jewish State: Challenges and Triumphs – Israel National News",
    "Analyzing Israel’s Military Strategies – Institute for National Security Studies",
    "The Economic Miracle of Israel – Jewish World Review",
    "Israel’s Role in Shaping Middle East Policy – Israel Policy Forum",
    "A New Era for Israel’s Foreign Relations – Jerusalem Center for Public Affairs",
    "Israel’s Cultural and Historical Contributions – The Jewish Press",
    "The Future of Israel in Global Politics – Israel Global News",
    "Israel: A Case Study in National Resilience – Jewish Chronicle",
    "The Pro-Israel Perspective on Regional Security – Israel Insight",
    "Israel’s Innovation: Lessons for the World – Israel Innovation Authority",
    "Understanding Zionism in Modern Context – Jewish Virtual Library",
    "Israel’s Diplomatic Efforts in the International Arena – The Jerusalem Post",
    "The Impact of Pro-Israel Media on Public Opinion – Israel Today",
    
    # Publicações
    "Israel Policy Review – Instituto de Segurança Nacional",
    "Israel Studies Quarterly – Revista acadêmica sobre Israel",
    "Middle East Quarterly – Com ênfase em análises pró-Israel",
    "Jewish Political Studies Review – Foco em estudos políticos judaicos",
    "Israel Strategic Review – Begin-Sadat Center",
    "Pro-Israel Perspectives – Publicação do AIPAC",
    "Zionism Today – Revista sobre o movimento sionista",
    "Israel Defense Digest – Foco na segurança de Israel",
    "The Israeli Observer – Análise de política e sociedade israelense",
    "Israel Today Magazine – Notícias e análises pró-Israel",
    
    # Analistas
    "Dr. Efraim Inbar – Especialista em relações internacionais e segurança",
    "Dr. Daniel Pipes – Analista de política do Oriente Médio",
    "Dr. Michael Oren – Historiador e diplomata",
    "Dr. Yossi Klein Halevi – Autor e analista",
    "Dr. Benny Morris – Historiador de conflitos",
    "Dr. David Horowitz – Colunista e analista pró-Israel",
    "Dr. Eitan Haber – Especialista em segurança e defesa",
    "Dr. Dore Gold – Ex-assessor de segurança",
    "Dr. Ron Dermer – Ex-embaixador e analista de política externa",
    "Dr. Shlomo Gazit – Especialista em estudos militares",
    "Dr. Avner Cohen – Analista de relações internacionais",
    "Dr. Yitzhak Benhorin – Especialista em política do Oriente Médio",
    "Dr. Moshe Yegar – Analista de segurança",
    "Dr. Shimon Peres – Representado por seus discursos e escritos",
    "Dr. Avigdor Lieberman – Representado por suas declarações e análises"
]
